services:
  # The NestJS Backend Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=flash_groups_db
    env_file:
      - ./server/.env

  # The React Frontend Service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose the Vite dev server port
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  # The PostgreSQL Database Service
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flash_groups_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: